<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" ignored="0" total="4" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="64928" started-at="2018-06-03T04:59:17Z" finished-at="2018-06-03T05:00:22Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="64928" started-at="2018-06-03T04:59:17Z" finished-at="2018-06-03T05:00:22Z">
      <class name="testScript.Test1">
        <test-method status="PASS" signature="launchBrowser()[pri:0, instance:testScript.Test1@3bfdc050]" name="launchBrowser" is-config="true" duration-ms="9630" started-at="2018-06-03T04:59:17Z" finished-at="2018-06-03T04:59:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="FAIL" signature="testFacebook()[pri:0, instance:testScript.Test1@3bfdc050]" name="testFacebook" duration-ms="14981" started-at="2018-06-03T04:59:27Z" finished-at="2018-06-03T04:59:42Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Facebook – log in or sign up1] but found [Facebook – log in or sign up]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Facebook – log in or sign up1] but found [Facebook – log in or sign up]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at testScript.Test1.testFacebook(Test1.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFacebook -->
        <test-method status="PASS" signature="closeBrowser(org.testng.ITestResult)[pri:0, instance:testScript.Test1@3bfdc050]" name="closeBrowser" is-config="true" duration-ms="1295" started-at="2018-06-03T04:59:42Z" finished-at="2018-06-03T04:59:43Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testFacebook status=FAILURE method=Test1.testFacebook()[pri:0, instance:testScript.Test1@3bfdc050] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- testScript.Test1 -->
      <class name="testScript.Test2">
        <test-method status="PASS" signature="launchBrowser()[pri:0, instance:testScript.Test2@1bce4f0a]" name="launchBrowser" is-config="true" duration-ms="4133" started-at="2018-06-03T04:59:43Z" finished-at="2018-06-03T04:59:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="FAIL" signature="instaTest()[pri:0, instance:testScript.Test2@1bce4f0a]" name="instaTest" duration-ms="8677" started-at="2018-06-03T04:59:47Z" finished-at="2018-06-03T04:59:56Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Instagram1] but found [Instagram]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Instagram1] but found [Instagram]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at testScript.Test2.instaTest(Test2.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- instaTest -->
        <test-method status="PASS" signature="closeBrowser(org.testng.ITestResult)[pri:0, instance:testScript.Test2@1bce4f0a]" name="closeBrowser" is-config="true" duration-ms="1302" started-at="2018-06-03T04:59:56Z" finished-at="2018-06-03T04:59:57Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=instaTest status=FAILURE method=Test2.instaTest()[pri:0, instance:testScript.Test2@1bce4f0a] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- testScript.Test2 -->
      <class name="testScript.Test3">
        <test-method status="PASS" signature="launchBrowser()[pri:0, instance:testScript.Test3@5e3a8624]" name="launchBrowser" is-config="true" duration-ms="4439" started-at="2018-06-03T04:59:57Z" finished-at="2018-06-03T05:00:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="FAIL" signature="testTwitter()[pri:0, instance:testScript.Test3@5e3a8624]" name="testTwitter" duration-ms="8166" started-at="2018-06-03T05:00:01Z" finished-at="2018-06-03T05:00:10Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Login on Twitter1] but found [Login on Twitter]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Login on Twitter1] but found [Login on Twitter]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at testScript.Test3.testTwitter(Test3.java:24)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTwitter -->
        <test-method status="PASS" signature="closeBrowser(org.testng.ITestResult)[pri:0, instance:testScript.Test3@5e3a8624]" name="closeBrowser" is-config="true" duration-ms="1187" started-at="2018-06-03T05:00:10Z" finished-at="2018-06-03T05:00:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testTwitter status=FAILURE method=Test3.testTwitter()[pri:0, instance:testScript.Test3@5e3a8624] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- testScript.Test3 -->
      <class name="testScript.Test4">
        <test-method status="PASS" signature="launchBrowser()[pri:0, instance:testScript.Test4@5c3bd550]" name="launchBrowser" is-config="true" duration-ms="4253" started-at="2018-06-03T05:00:11Z" finished-at="2018-06-03T05:00:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="FAIL" signature="testLinkedIn()[pri:0, instance:testScript.Test4@5c3bd550]" name="testLinkedIn" duration-ms="5521" started-at="2018-06-03T05:00:15Z" finished-at="2018-06-03T05:00:21Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Sign Up | LinkedIn1] but found [Sign Up | LinkedIn]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Sign Up | LinkedIn1] but found [Sign Up | LinkedIn]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at testScript.Test4.testLinkedIn(Test4.java:24)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLinkedIn -->
        <test-method status="PASS" signature="closeBrowser(org.testng.ITestResult)[pri:0, instance:testScript.Test4@5c3bd550]" name="closeBrowser" is-config="true" duration-ms="1283" started-at="2018-06-03T05:00:21Z" finished-at="2018-06-03T05:00:22Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testLinkedIn status=FAILURE method=Test4.testLinkedIn()[pri:0, instance:testScript.Test4@5c3bd550] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- testScript.Test4 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
